name: emsim
channels:
- defaults
dependencies:
- pip=19.3.1
- python=3.7.6
- requests=2.22.0
- numpy=1.18.1
- scipy=1.4.1
- pandas=1.0.3
- arrow=0.13.1
- future=0.16.0
- pip:
    - geojson==2.3.*
    - polyline==1.3.*
    - geopy==1.21.*
    - attrdict==2.0.0
    - bson==0.5.9
